// Shared by supabase/functions/create-order (HTTP webhook, used by the website
// checkout and by the ElevenLabs voice agent's Server Tool) and by
// supabase/functions/whatsapp-webhook (called in-process, no HTTP round-trip,
// from the WhatsApp tool-use loop). Keeping this in one place means the price
// re-validation logic can't drift between the three callers.

// deno-lint-ignore-file no-explicit-any
export interface OrderItemInput {
  product_id?: string;
  /** Nombre exacto devuelto por buscar_producto; permite recuperar un UUID mal copiado. */
  product_name?: string;
  /** Unidades cobrables del catálogo (compatibilidad con web/admin). */
  quantity?: number;
  /** Piezas/unidades que pidió el cliente, para voz y WhatsApp. */
  requested_quantity?: number;
  /** Elección confirmada para cada renglón de tacos. */
  tortilla?: TortillaChoice;
}

export interface CreateOrderPayload {
  branch_slug?: string;
  branch_name?: string;
  customer_name: string;
  customer_phone: string;
  customer_address?: string;
  items: OrderItemInput[];
  source?: "web" | "voice" | "whatsapp" | "admin";
  call_transcript?: string;
  call_recording_url?: string;
  // Instrucciones especiales del cliente ("sin cebolla", "tocar el
  // timbre") — antes se reconocían y repetían en el chat pero nunca
  // llegaban a cocina porque `orders` no tenía dónde guardarlas.
  notes?: string;
  // Pedido real de Javier el 4-sep-2026: el agente (voz y WhatsApp) SIEMPRE
  // pregunta "efectivo o tarjeta" antes de crear el pedido (paso 6/7 del
  // flujo real), pero esa respuesta nunca se guardaba en ningún lado —
  // Historial de Órdenes no tenía nada real que mostrar como forma de pago.
  payment_method?: "efectivo" | "tarjeta";
  // Stable retry key generated by the caller for one checkout intent. It is
  // hashed before persistence and never treated as an authorization token.
  idempotency_key?: string;
  /** ID inyectado por ElevenLabs; no lo elige ni lo copia el LLM. */
  conversation_id?: string;
  // Variable inyectada por ElevenLabs desde el widget de vista previa. El
  // endpoint solo la respeta cuando el webhook también trae el secreto del
  // tool; un checkout público nunca puede convertir su pedido en simulación.
  modo_prueba?: unknown;
  // Confirmación explícita obtenida por el agente cuando el pedido incluye
  // alcohol. El servidor no acepta true implícito ni una respuesta ambigua.
  adult_confirmed?: boolean;
  /** Complementos sin costo que solo se mandan cuando el cliente los pide. */
  requested_complements?: RequestedComplement[];
  /** Complementos de cortesía que el cliente pidió omitir. */
  omit_default_complements?: DefaultComplement[];
}

export type RequestedComplement = "salsa_habanero" | "crema_ajo";
export type DefaultComplement =
  | "salsa_verde"
  | "salsa_roja"
  | "limones"
  | "cebolla";

export class OrderValidationError extends Error {}
export class OrderConflictError extends OrderValidationError {}

export function isValidVoiceConversationId(value: unknown): value is string {
  return typeof value === "string" && /^conv_[a-z0-9]{10,190}$/i.test(value);
}

/** Un marcador vencido nunca deja de ser una simulación para volverse real. */
export async function resolveVoicePreviewRestaurant(
  supabase: any,
  conversationId: unknown,
  now = Date.now(),
): Promise<string | null> {
  if (!isValidVoiceConversationId(conversationId)) {
    throw new OrderValidationError(
      "conversation_id válido es requerido para voz",
    );
  }
  const { data: session, error } = await supabase.from("voice_preview_sessions")
    .select("restaurant_id, expires_at")
    .eq("conversation_id", conversationId)
    .maybeSingle();
  if (error) throw error;
  if (!session) return null;
  if (!(Date.parse(session.expires_at) > now)) {
    throw new OrderValidationError(
      "La vista previa expiró. Inicia una conversación de prueba nueva.",
    );
  }
  return session.restaurant_id;
}

/** Inserción inmutable: un reintento nunca cambia el tenant ni renueva el TTL. */
export async function registerVoicePreviewSession(
  supabase: any,
  session: {
    conversation_id: string;
    restaurant_id: string;
    agent_id: string;
    created_by: string;
  },
  conversation: { agent_id?: unknown; conversation_id?: unknown },
) {
  if (!isValidVoiceConversationId(session.conversation_id)) {
    throw new OrderValidationError("conversation_id inválido");
  }
  if (
    conversation?.agent_id !== session.agent_id ||
    conversation?.conversation_id !== session.conversation_id
  ) {
    throw new OrderConflictError("La conversación no pertenece a este agente");
  }
  const { error } = await supabase.from("voice_preview_sessions").upsert({
    ...session,
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
  }, { onConflict: "conversation_id", ignoreDuplicates: true });
  if (error) throw error;
  const { data: stored, error: readError } = await supabase
    .from("voice_preview_sessions")
    .select("restaurant_id, agent_id, expires_at")
    .eq("conversation_id", session.conversation_id)
    .single();
  if (readError) throw readError;
  if (
    stored.restaurant_id !== session.restaurant_id ||
    stored.agent_id !== session.agent_id
  ) {
    throw new OrderConflictError(
      "La conversación ya pertenece a otro agente o restaurante",
    );
  }
  if (!(Date.parse(stored.expires_at) > Date.now())) {
    throw new OrderValidationError(
      "La vista previa expiró. Inicia una conversación de prueba nueva.",
    );
  }
  return stored;
}

export function isTrustedVoicePreview(
  toolAuthorized: boolean,
  value: unknown,
): boolean {
  return toolAuthorized &&
    (value === true ||
      (typeof value === "string" && value.toLowerCase() === "true"));
}

async function sha256Hex(value: string): Promise<string> {
  const bytes = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(value),
  );
  return Array.from(new Uint8Array(bytes))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

function invalidOptionalString(value: unknown, maxLength: number): boolean {
  return value !== undefined &&
    value !== null &&
    (typeof value !== "string" || value.length > maxLength);
}

// El mismo cliente real llega con el teléfono en formatos distintos según el
// canal: ElevenLabs transcribe lo que dice en voz (con o sin espacios/guiones,
// a veces sin el "52" de México), Meta manda el wa_id de WhatsApp sin "+" y a
// veces con un "1" extra después del "52" (quirk real y documentado de la
// Cloud API para números mexicanos migrados de la app clásica de WhatsApp), y
// el checkout web puede mandar cualquier formato que el cliente haya tecleado.
// Un match exacto (`.eq("phone", phone)`) sin normalizar hacía que el MISMO
// cliente real apareciera como "nuevo" cada vez que el formato variaba
// levemente — perdiendo en silencio su tier VIP, direcciones guardadas e
// historial, y creando un customer_id duplicado en vez de reconocerlo.
// Confirmado en vivo el 3-sep-2026 (auditoría multi-agente): dos filas reales
// de `customers` para la misma persona, cada una con order_count=1.
//
// Normaliza a los últimos 10 dígitos (número nacional significativo
// mexicano) — absorbe "+", espacios, guiones, "52"/"521" de país, y es
// estable sin importar cuál de los formatos reales llegue primero.
//
// Bug real encontrado en la auditoría adversarial del 3-sep-2026: la
// versión original devolvía soloDigitos SIN mínimo de longitud — un
// identificador sin dígitos reales (ej. un phone de prueba "widget-<texto
// sin números>") se reducía a "" (string vacío), y CUALQUIER otra
// conversación cuyo identificador tampoco tuviera dígitos colapsaba en el
// MISMO customer_id vacío — mezclando historial/order_count entre clientes
// que no tienen nada que ver. Confirmado en la base real: dos customers
// distintos con phone "" y "01". Fix: exigir un mínimo real de dígitos (7,
// el mínimo plausible de un teléfono real) antes de normalizar — si no se
// alcanza, se usa el string original completo (no el fragmento de dígitos)
// para no perder la unicidad de identificadores no numéricos.
export function normalizePhone(phone: string): string {
  const soloDigitos = phone.replace(/\D/g, "");
  if (soloDigitos.length >= 7) return soloDigitos.slice(-10);
  return phone.trim();
}

/**
 * Valida el número que el agente de voz entendió antes de buscar o crear.
 * Acepta el número nacional de 10 dígitos y las dos formas reales de México
 * que pueden traer +52/521. No recorta silenciosamente 11 o 12 dígitos
 * arbitrarios: eso podría asociar el pedido con otra persona.
 */
export function canonicalizeMexicanPhone(phone: string): string | null {
  const digits = phone.replace(/\D/g, "");
  if (digits.length === 10) return digits;
  if (digits.length === 12 && digits.startsWith("52")) return digits.slice(2);
  if (digits.length === 13 && digits.startsWith("521")) return digits.slice(3);
  return null;
}

export const DEFAULT_COMPLEMENTS: readonly DefaultComplement[] = [
  "salsa_verde",
  "salsa_roja",
  "limones",
  "cebolla",
];

const COMPLEMENT_LABELS: Record<
  DefaultComplement | RequestedComplement,
  string
> = {
  salsa_verde: "salsa verde",
  salsa_roja: "salsa roja",
  limones: "limones",
  cebolla: "cebolla",
  salsa_habanero: "salsa habanero",
  crema_ajo: "crema de ajo",
};

export function buildComplementNotes(
  notes?: string,
  requested: RequestedComplement[] = [],
  omitted: DefaultComplement[] = [],
): string {
  const omittedSet = new Set(omitted);
  const included = DEFAULT_COMPLEMENTS.filter((item) => !omittedSet.has(item));
  const uniqueRequested = [...new Set(requested)];
  const lines = [notes?.trim()].filter(Boolean) as string[];
  lines.push(
    included.length > 0
      ? `Complementos incluidos: ${
        included.map((item) => COMPLEMENT_LABELS[item]).join(", ")
      }.`
      : "No enviar complementos de cortesía.",
  );
  if (uniqueRequested.length > 0) {
    lines.push(
      `Complementos solicitados: ${
        uniqueRequested.map((item) => COMPLEMENT_LABELS[item]).join(", ")
      }.`,
    );
  }
  return lines.join("\n");
}

// Hallazgo real de la auditoría adversarial (3-sep-2026): el agente le dijo
// a un cliente de prueba "no procesamos ni guardamos los datos que
// compartiste por chat" al mandar un número de tarjeta completo — pero el
// mensaje se guardaba tal cual, número/vencimiento/CVV incluidos, en texto
// plano en whatsapp_conversations.messages. La afirmación del agente era
// falsa. Este helper redacta patrones de tarjeta/CVV/vencimiento ANTES de
// guardar cualquier mensaje real del cliente, para que esa afirmación sea
// cierta de verdad — se llama desde whatsapp-webhook y whatsapp-widget-chat
// justo antes de hacer push del mensaje del usuario al historial.
export function redactSensitiveInfo(text: string): string {
  return (
    text
      // Número de tarjeta: 13-19 dígitos, con o sin espacios/guiones entre grupos.
      .replace(/\b(?:\d[ -]?){13,19}\b/g, "[tarjeta oculta]")
      // CVV/CVC explícito con etiqueta.
      .replace(/\b(?:cvv|cvc|c\.?v\.?v\.?)\s*:?\s*\d{3,4}\b/gi, "[cvv oculto]")
      // Vencimiento tipo MM/YY o MM/YYYY, normalmente junto a "exp"/"vencimiento" en el mismo mensaje.
      .replace(/\b\d{1,2}\/\d{2,4}\b/g, "[vencimiento oculto]")
  );
}

// Bug real confirmado el 3-sep-2026 (auditoría de voz, 9 agentes): "cerveza
// Sol" y "coctel Margarita" devolvían CERO resultados pese a que "Sol" y
// "Margarita" sí están disponibles — el match es AND de todos los tokens
// contra products.name, y "cerveza"/"coctel" nunca aparecen literalmente en
// el nombre real (los productos se llaman "Sol", "Indio", "Margarita", no
// "Cerveza Sol"). El agente terminó diciéndole al cliente que no había
// cervezas ni cócteles disponibles, siendo falso — se sumaron estas palabras
// de categoría a las stopwords, igual que ya se hace con conectores, para
// que solo el nombre real de la bebida entre al match.
const STOPWORDS_BUSQUEDA = new Set([
  "de",
  "del",
  "la",
  "el",
  "los",
  "las",
  "un",
  "una",
  "unos",
  "unas",
  "y",
  "con",
  "para",
  "al",
  "quiero",
  "quisiera",
  "dame",
  "deme",
  "ponme",
  "agrega",
  "añade",
  "uno",
  "dos",
  "tres",
  "cuatro",
  "cinco",
  "seis",
  "siete",
  "ocho",
  "nueve",
  "diez",
  "once",
  "doce",
  "trece",
  "catorce",
  "quince",
  "dieciséis",
  "dieciseis",
  "diecisiete",
  "dieciocho",
  "diecinueve",
  "veinte",
  "cerveza",
  "cervezas",
  "coctel",
  "cocteles",
  "cóctel",
  "cócteles",
]);

// Tokenizador compartido de buscar_producto (voz vía buscar-producto/index.ts
// y WhatsApp vía whatsapp-agent-core.ts) — antes cada canal tenía su propia
// copia duplicada de esta lógica (riesgo real de que un fix se aplicara a
// un canal y no al otro, señalado en la auditoría del 3-sep-2026).
//
// Dos gaps reales encontrados DESPUÉS de la tokenización básica, verificando
// en vivo con curl: (1) "tacos al pastor" (plural, como diría un cliente
// real) no encontraba "Taco Al Pastor (individual)" — el catálogo mezcla
// nombres en singular y en plural, y el ILIKE exacto de "tacos" no es
// substring de "Taco"; (2) "500g"/"1kg" (pegado, sin espacio, como lo
// escribiría el modelo o un cliente) no encontraba "Arrachera — 500 g" —
// el nombre real SIEMPRE lleva espacio antes de la unidad.
export function tokenizeForProductSearch(query: string): string[] {
  // Bug real encontrado el 3-sep-2026 (pruebas de "vida cotidiana"): un
  // cliente real dice "un kilo de bistec" o "medio kilo de arrachera" — la
  // palabra "kilo" nunca aparece en el nombre real del producto (que dice
  // "1 kg" o "500 g", nunca "kilo"), así que el token "kilo" no hacía match
  // con nada y el agente decía (falso) que el producto no existía, aunque
  // sí estaba disponible. Se normalizan las frases reales de kilos ANTES
  // de tokenizar, a la forma pegada que ya sabe resolver el bloque de abajo
  // (igual que "500g"/"1kg").
  const normalizada = query
    .toLowerCase()
    .replace(/\bcero\s+punto\s+cero\b/g, "0.0")
    .replace(/tres\s+cuartos?\s+de\s+kilo/g, "750g")
    .replace(/cuarto\s+de\s+kilo/g, "250g")
    .replace(/medio\s+kilo/g, "500g")
    .replace(/\bkilos?\b/g, "kg");

  const raw = normalizada
    .split(/\s+/)
    .filter((t) => t.length > 1 && !STOPWORDS_BUSQUEDA.has(t));

  const tokens: string[] = [];
  for (const t of raw) {
    const pesoMatch = t.match(/^(\d+)(kg|gr|g)$/);
    if (pesoMatch) {
      // separa el número de la unidad — así hace match sin importar si el
      // nombre real trae espacio entre ellos o no.
      tokens.push(pesoMatch[1], pesoMatch[2] === "gr" ? "g" : pesoMatch[2]);
      continue;
    }
    // singulariza un plural regular simple (tacos -> taco) — de sobra para
    // encontrar más, nunca para encontrar menos: un token más corto es un
    // substring MÁS permisivo, nunca más estricto.
    tokens.push(t.length > 4 && t.endsWith("s") ? t.slice(0, -1) : t);
  }
  return tokens.length > 0 ? tokens : [query.toLowerCase()];
}

export interface ProductoEncontrado {
  id: string;
  name: string;
  price: number;
  /**
   * Cantidad fija de piezas del paquete si el producto se vende como
   * paquete indivisible (ej. 3 para "Tacos de Bistec de Res (orden de 3)"),
   * 1 si se vende por pieza individual ("... (individual)" / "Orden
   * individual" en su description), o null si no aplica esa noción de
   * "piezas por paquete" (bebidas, platillos completos, kilos, etc.).
   * Se calcula del name+description real en vez de dejar que el LLM tenga
   * que inferirlo de un paréntesis en el texto — bug real confirmado
   * 4-sep-2026: el agente de voz aceptó "un taco de bistec" sin corregir
   * al cliente pese a que el prompt ya le decía que revisara el nombre;
   * un campo estructurado explícito es más difícil de pasar por alto que
   * un patrón de texto libre.
   */
  pack_size: number | null;
  /** El agente debe obtener un sí claro de mayoría de edad antes de cotizar. */
  requires_adult_confirmation?: boolean;
}

export interface RequestedOrderItemInput {
  product_id?: string;
  product_name?: string;
  requested_quantity: number;
  tortilla?: TortillaChoice;
}

export type TortillaChoice = "maiz" | "harina";

export interface QuotedOrderLine {
  product_id: string;
  name: string;
  price: number;
  requested_quantity: number;
  pack_size: number | null;
  /** Cantidad de unidades del catálogo que se cobran/guardan. */
  quantity: number;
  tortilla: TortillaChoice | null;
  requires_adult_confirmation: boolean;
  line_total: number;
}

export interface OrderQuote {
  items: Array<{
    product_id: string;
    quantity: number;
    tortilla?: TortillaChoice;
  }>;
  lines: QuotedOrderLine[];
  total: number;
}

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function comparableProductName(value: string): string {
  return value.normalize("NFC").trim().replace(/\s+/g, " ").toLocaleLowerCase(
    "es-MX",
  );
}

/**
 * Resuelve cada renglón al producto canónico. Un UUID inválido o inexistente
 * puede recuperarse únicamente con el nombre exacto que devolvió
 * buscar_producto. Si un UUID válido apunta a un nombre distinto se rechaza:
 * jamás se cambia silenciosamente lo que se va a cobrar/preparar.
 */
export function resolveOrderItemsAgainstProducts(
  items: RequestedOrderItemInput[],
  products: ProductoEncontrado[],
): Array<
  RequestedOrderItemInput & { product_id: string; product_name: string }
> {
  return items.map((item) => {
    const requestedId = typeof item?.product_id === "string"
      ? item.product_id.trim()
      : "";
    const requestedName = typeof item?.product_name === "string"
      ? item.product_name.trim()
      : "";
    const byId = requestedId
      ? products.find((product) => product.id === requestedId)
      : undefined;
    const byName = requestedName
      ? products.find((product) =>
        comparableProductName(product.name) ===
          comparableProductName(requestedName)
      )
      : undefined;

    if (
      byId && requestedName &&
      comparableProductName(byId.name) !== comparableProductName(requestedName)
    ) {
      throw new OrderValidationError(
        `El identificador y el nombre del producto no coinciden: ${requestedName}. Vuelve a usar exactamente el resultado de buscar_producto.`,
      );
    }
    const product = byId ?? byName;
    if (!product) {
      const reference = requestedName || requestedId || "sin identificador";
      throw new OrderValidationError(
        `Producto no disponible: ${reference}. Vuelve a llamar buscar_producto y copia también product_name.`,
      );
    }
    return {
      ...item,
      product_id: product.id,
      product_name: product.name,
    };
  });
}

function mapBranchProducts(rows: any[] | null): ProductoEncontrado[] {
  return (rows ?? [])
    .filter((row: any) => row.is_available)
    .map((row: any) => ({
      id: row.products.id,
      name: row.products.name,
      price: Number(row.price),
      pack_size: extraerPackSize(row.products.name, row.products.description),
      requires_adult_confirmation: requiresAdultConfirmation(
        row.products.name,
        row.products.categories?.name,
      ),
    }));
}

async function resolveBranchOrderItems(
  supabase: any,
  branchId: string,
  items: RequestedOrderItemInput[],
): Promise<{
  items: Array<
    RequestedOrderItemInput & { product_id: string; product_name: string }
  >;
  products: ProductoEncontrado[];
}> {
  if (!Array.isArray(items) || items.length === 0 || items.length > 100) {
    throw new OrderValidationError("El pedido no tiene productos válidos");
  }
  for (const item of items) {
    const idValid = typeof item?.product_id === "string" &&
      UUID_PATTERN.test(item.product_id);
    const nameValid = typeof item?.product_name === "string" &&
      item.product_name.trim().length > 0 && item.product_name.length <= 240;
    if (!idValid && !nameValid) {
      throw new OrderValidationError(
        "Cada producto requiere un UUID válido o el product_name exacto devuelto por buscar_producto.",
      );
    }
  }

  const select =
    "price, is_available, products!inner(id, name, description, categories(name))";
  const validIds = [
    ...new Set(
      items
        .map((item) => item.product_id)
        .filter((id): id is string =>
          typeof id === "string" && UUID_PATTERN.test(id)
        ),
    ),
  ];
  const exactNames = [
    ...new Set(
      items
        .map((item) => item.product_name?.trim())
        .filter((name): name is string => Boolean(name)),
    ),
  ];
  const rows: any[] = [];

  if (validIds.length > 0) {
    const { data, error } = await supabase.from("branch_products")
      .select(select)
      .eq("branch_id", branchId)
      .in("product_id", validIds);
    if (error) throw error;
    rows.push(...(data ?? []));
  }
  if (exactNames.length > 0) {
    const { data, error } = await supabase.from("branch_products")
      .select(select)
      .eq("branch_id", branchId)
      .in("products.name", exactNames);
    if (error) throw error;
    rows.push(...(data ?? []));
  }

  const byId = new Map<string, ProductoEncontrado>();
  for (const product of mapBranchProducts(rows)) byId.set(product.id, product);
  const products = [...byId.values()];
  return {
    items: resolveOrderItemsAgainstProducts(items, products),
    products,
  };
}

function extraerPackSize(
  name: string,
  description: string | null,
): number | null {
  const texto = `${name} ${description ?? ""}`;
  const orden = texto.match(/orden de (\d+)/i);
  if (orden) return parseInt(orden[1], 10);
  if (/individual/i.test(texto)) return 1;
  return null;
}

/**
 * Traduce lo que pidió el cliente (piezas/unidades habladas) a unidades
 * cobrables del catálogo. El cálculo vive fuera del LLM para que
 * "8 individuales" nunca se convierta en "máximo 1", y para que una orden
 * de 3 se cobre una sola vez, no tres.
 */
export function buildOrderQuoteFromProducts(
  requestedItems: RequestedOrderItemInput[],
  products: ProductoEncontrado[],
  options: { adult_confirmed?: boolean } = {},
): OrderQuote {
  if (!Array.isArray(requestedItems) || requestedItems.length === 0) {
    throw new OrderValidationError("El pedido no tiene productos");
  }
  if (requestedItems.length > 100) {
    throw new OrderValidationError("Productos o cantidades inválidos");
  }

  const lines: QuotedOrderLine[] = [];
  let total = 0;
  for (const item of requestedItems) {
    if (
      !item || typeof item.product_id !== "string" ||
      item.product_id.length > 64 ||
      !Number.isInteger(item.requested_quantity) ||
      item.requested_quantity < 1 || item.requested_quantity > 100
    ) {
      throw new OrderValidationError("Productos o cantidades inválidos");
    }
    const product = products.find((candidate) =>
      candidate.id === item.product_id
    );
    if (!product) {
      throw new OrderValidationError(
        `Producto no disponible: ${item.product_id}`,
      );
    }

    if (
      product.requires_adult_confirmation === true &&
      options.adult_confirmed !== true
    ) {
      throw new OrderValidationError(
        `Antes de cotizar ${product.name}, confirma de forma explícita que quien recibe el pedido es mayor de edad.`,
      );
    }

    if (
      item.tortilla !== undefined && item.tortilla !== "maiz" &&
      item.tortilla !== "harina"
    ) {
      throw new OrderValidationError(
        `Tortilla inválida para ${product.name}: elige maíz o harina.`,
      );
    }
    const requiresTortilla = /\btacos?\b/i.test(product.name);
    if (requiresTortilla && !item.tortilla) {
      throw new OrderValidationError(
        `Antes de continuar, confirma si ${product.name} va con tortilla de maíz o harina.`,
      );
    }
    // Los modelos a veces copian el último enum de tortilla a todos los
    // renglones del tool call. El backend conserva la elección solo donde
    // semánticamente aplica; una Coca-Cola o una pizza nunca carga tortilla.
    const tortilla = requiresTortilla ? item.tortilla ?? null : null;

    const packSize = product.pack_size;
    if (packSize !== null && (!Number.isInteger(packSize) || packSize < 1)) {
      throw new OrderValidationError(
        `Presentación inválida para ${product.name}`,
      );
    }
    if (packSize && packSize > 1 && item.requested_quantity % packSize !== 0) {
      const lower = Math.floor(item.requested_quantity / packSize) * packSize;
      const upper = Math.ceil(item.requested_quantity / packSize) * packSize;
      const options = lower >= packSize ? `${lower} o ${upper}` : String(upper);
      throw new OrderValidationError(
        `${product.name} solo se vende en órdenes de ${packSize} piezas. ` +
          `Pediste ${item.requested_quantity}; puedes pedir ${options}.`,
      );
    }

    const quantity = packSize && packSize > 1
      ? item.requested_quantity / packSize
      : item.requested_quantity;
    const price = Number(product.price);
    const lineTotal = Math.round(price * quantity * 100) / 100;
    total = Math.round((total + lineTotal) * 100) / 100;
    lines.push({
      product_id: product.id,
      name: product.name,
      price,
      requested_quantity: item.requested_quantity,
      pack_size: packSize,
      quantity,
      tortilla,
      requires_adult_confirmation: product.requires_adult_confirmation === true,
      line_total: lineTotal,
    });
  }

  return {
    items: lines.map((line) => ({
      product_id: line.product_id,
      quantity: line.quantity,
      ...(line.tortilla ? { tortilla: line.tortilla } : {}),
    })),
    lines,
    total,
  };
}

export function requiresAdultConfirmation(
  productName: string,
  categoryName: string | null | undefined,
): boolean {
  if (!/^(cervezas|licores y cocktails)$/i.test(categoryName ?? "")) {
    return false;
  }
  return !/(?:\bsin\s+alcohol\b|\b0[.,]0\b)/i.test(productName);
}

/**
 * Búsqueda real de productos disponibles en una sucursal, compartida por el
 * agente de voz (buscar-producto/index.ts) y el de WhatsApp
 * (whatsapp-agent-core.ts) — antes cada uno traía su propia copia de esta
 * consulta (mismo texto, dos archivos) y las dos comparaban el query del
 * cliente SOLO contra `products.name`. Bug real confirmado 4-sep-2026: un
 * cliente pidió "una pizza" y el agente dijo que no había disponible, pese a
 * que sí existe un producto real ("Quesobich de Queso", categoría "Pizza
 * Quesobich") que es literalmente una pizza — la palabra "pizza" solo vive en
 * su `description` y en el nombre de su categoría, nunca en `products.name`,
 * así que la búsqueda angosta no lo encontraba. Ahora un token hace match si
 * aparece en el name, la description, la categoría, O cualquier alias de
 * `products.search_keywords` (columna sembrada a mano para ~250 productos
 * reales el 4-sep-2026) — todos los tokens siguen siendo obligatorios (AND),
 * solo se amplió EN QUÉ campo puede aparecer cada uno.
 */
export async function buscarProductosCore(
  supabase: any,
  {
    branchId,
    restaurantId,
    query,
  }: {
    branchId: string;
    restaurantId: string;
    query: string;
  },
): Promise<ProductoEncontrado[]> {
  const tokens = tokenizeForProductSearch(query);

  const { data: rows, error } = await supabase
    .from("branch_products")
    .select(
      "price, is_available, products!inner(id, name, description, restaurant_id, search_keywords, categories(name))",
    )
    .eq("branch_id", branchId)
    .eq("is_available", true)
    .eq("products.restaurant_id", restaurantId)
    .limit(400);
  if (error) throw error;

  const coincide = (r: any) => {
    const producto = r.products;
    const textoPlano = [
      producto.name,
      producto.description,
      producto.categories?.name,
    ]
      .filter(Boolean)
      .join(" ")
      .toLowerCase();
    const alias: string[] = producto.search_keywords ?? [];
    return tokens.every(
      (t) =>
        textoPlano.includes(t) ||
        alias.some((a) => a.toLowerCase().includes(t)),
    );
  };

  return (rows ?? [])
    .filter(coincide)
    .slice(0, 8)
    .map((r: any) => ({
      id: r.products.id,
      name: r.products.name,
      price: r.price,
      pack_size: extraerPackSize(r.products.name, r.products.description),
      requires_adult_confirmation: requiresAdultConfirmation(
        r.products.name,
        r.products.categories?.name,
      ),
    }));
}

export async function quoteOrderCore(
  supabase: any,
  payload: {
    branch_slug: string;
    items: RequestedOrderItemInput[];
    adult_confirmed?: boolean;
  },
): Promise<
  OrderQuote & {
    branch_id: string;
    branch_name: string;
    restaurant_id: string;
  }
> {
  if (
    !payload || typeof payload !== "object" ||
    typeof payload.branch_slug !== "string" || !payload.branch_slug.trim() ||
    payload.branch_slug.length > 100
  ) {
    throw new OrderValidationError("branch_slug es requerido");
  }

  const { data: branch, error: branchError } = await supabase
    .from("branches")
    .select("id, name, is_active, restaurant_id")
    .eq("slug", payload.branch_slug)
    .maybeSingle();
  if (branchError) throw branchError;
  if (!branch || !branch.is_active) {
    throw new OrderValidationError(
      `Sucursal '${payload.branch_slug}' no encontrada o inactiva`,
    );
  }

  const resolved = await resolveBranchOrderItems(
    supabase,
    branch.id,
    payload.items ?? [],
  );
  const quote = buildOrderQuoteFromProducts(resolved.items, resolved.products, {
    adult_confirmed: payload.adult_confirmed,
  });
  return {
    ...quote,
    branch_id: branch.id,
    branch_name: branch.name,
    restaurant_id: branch.restaurant_id,
  };
}

/**
 * Contrato único para pedidos reales y simulados. Mantenerlo puro permite que
 * la vista previa pruebe exactamente las mismas entradas sin escribir datos.
 */
export function validateCreateOrderPayload(
  rawPayload: CreateOrderPayload,
): CreateOrderPayload {
  if (
    !rawPayload || typeof rawPayload !== "object" || Array.isArray(rawPayload)
  ) {
    throw new OrderValidationError("Payload inválido");
  }
  if (
    (!(typeof rawPayload.branch_slug === "string" &&
      rawPayload.branch_slug.trim()) &&
      !(typeof rawPayload.branch_name === "string" &&
        rawPayload.branch_name.trim())) ||
    typeof rawPayload.customer_name !== "string" ||
    !rawPayload.customer_name.trim() ||
    typeof rawPayload.customer_phone !== "string" ||
    !rawPayload.customer_phone.trim()
  ) {
    throw new OrderValidationError(
      "branch_slug (o branch_name), customer_name y customer_phone son requeridos",
    );
  }
  if (
    rawPayload.customer_name.trim().length > 160 ||
    rawPayload.customer_phone.length > 64 ||
    invalidOptionalString(rawPayload.branch_slug, 100) ||
    invalidOptionalString(rawPayload.branch_name, 160) ||
    invalidOptionalString(rawPayload.customer_address, 1000) ||
    invalidOptionalString(rawPayload.notes, 2000) ||
    invalidOptionalString(rawPayload.conversation_id, 200) ||
    invalidOptionalString(rawPayload.call_transcript, 20000) ||
    invalidOptionalString(rawPayload.call_recording_url, 2000)
  ) {
    throw new OrderValidationError(
      "Uno o más campos exceden el tamaño permitido",
    );
  }
  if (
    rawPayload.idempotency_key !== undefined &&
    (typeof rawPayload.idempotency_key !== "string" ||
      !rawPayload.idempotency_key.trim() ||
      rawPayload.idempotency_key.length > 200)
  ) {
    throw new OrderValidationError("idempotency_key inválido");
  }
  if (
    rawPayload.adult_confirmed !== undefined &&
    typeof rawPayload.adult_confirmed !== "boolean"
  ) {
    throw new OrderValidationError("adult_confirmed debe ser booleano");
  }
  const agentOrder = rawPayload.source === "voice" ||
    rawPayload.source === "whatsapp";
  if (
    agentOrder &&
    (typeof rawPayload.customer_address !== "string" ||
      !rawPayload.customer_address.trim())
  ) {
    throw new OrderValidationError(
      "La dirección completa de entrega es requerida",
    );
  }
  if (
    (agentOrder && rawPayload.payment_method !== "efectivo" &&
      rawPayload.payment_method !== "tarjeta") ||
    (!agentOrder && rawPayload.payment_method !== undefined &&
      rawPayload.payment_method !== "efectivo" &&
      rawPayload.payment_method !== "tarjeta")
  ) {
    throw new OrderValidationError(
      "La forma de pago debe ser efectivo o tarjeta",
    );
  }
  const voicePhone = rawPayload.source === "voice"
    ? canonicalizeMexicanPhone(rawPayload.customer_phone)
    : null;
  if (rawPayload.source === "voice" && !voicePhone) {
    throw new OrderValidationError(
      "Teléfono inválido: confirma exactamente 10 dígitos y vuelve a leerlos al cliente en grupos 3-3-4.",
    );
  }
  const payload: CreateOrderPayload = {
    ...rawPayload,
    branch_slug: rawPayload.branch_slug?.trim() || undefined,
    branch_name: rawPayload.branch_name?.trim() || undefined,
    customer_name: rawPayload.customer_name.trim(),
    customer_phone: voicePhone ?? normalizePhone(rawPayload.customer_phone),
    customer_address: rawPayload.customer_address?.trim(),
  };
  if (!Array.isArray(payload.items) || payload.items.length === 0) {
    throw new OrderValidationError("El pedido no tiene productos");
  }
  if (
    payload.items.length > 100 ||
    payload.items.some(
      (item) => {
        if (
          !item || typeof item !== "object" || Array.isArray(item) ||
          (item.product_id !== undefined &&
            (typeof item.product_id !== "string" ||
              item.product_id.length > 64)) ||
          (item.product_name !== undefined &&
            (typeof item.product_name !== "string" ||
              item.product_name.length > 240)) ||
          (!(typeof item.product_id === "string" &&
            UUID_PATTERN.test(item.product_id)) &&
            !(typeof item.product_name === "string" &&
              item.product_name.trim())) ||
          (item.tortilla !== undefined && item.tortilla !== "maiz" &&
            item.tortilla !== "harina")
        ) return true;
        const hasQuantity = item.quantity !== undefined;
        const hasRequested = item.requested_quantity !== undefined;
        if (hasQuantity === hasRequested) return true;
        const value = hasRequested ? item.requested_quantity : item.quantity;
        return !Number.isInteger(value) || (value as number) < 1 ||
          (value as number) > 100;
      },
    )
  ) {
    throw new OrderValidationError("Productos o cantidades inválidos");
  }
  const validRequestedComplements = new Set<RequestedComplement>([
    "salsa_habanero",
    "crema_ajo",
  ]);
  const validDefaultComplements = new Set<DefaultComplement>(
    DEFAULT_COMPLEMENTS,
  );
  if (
    (payload.requested_complements !== undefined &&
      (!Array.isArray(payload.requested_complements) ||
        payload.requested_complements.length > validRequestedComplements.size ||
        payload.requested_complements.some((item) =>
          !validRequestedComplements.has(item)
        ))) ||
    (payload.omit_default_complements !== undefined &&
      (!Array.isArray(payload.omit_default_complements) ||
        payload.omit_default_complements.length >
          validDefaultComplements.size ||
        payload.omit_default_complements.some((item) =>
          !validDefaultComplements.has(item)
        )))
  ) {
    throw new OrderValidationError("Complementos inválidos");
  }
  return payload;
}

export async function prepareCreateOrder(
  supabase: any,
  rawPayload: CreateOrderPayload,
) {
  const payload = validateCreateOrderPayload(rawPayload);

  const branchQuery = supabase
    .from("branches")
    .select("id, name, is_active, restaurant_id");
  const { data: branch, error: branchError } = await (
    payload.branch_slug
      ? branchQuery.eq("slug", payload.branch_slug)
      : branchQuery.eq("name", payload.branch_name)
  ).maybeSingle();

  if (branchError) throw branchError;
  if (!branch || !branch.is_active) {
    throw new OrderValidationError(
      `Sucursal '${
        payload.branch_slug ?? payload.branch_name
      }' no encontrada o inactiva`,
    );
  }

  // Precio y disponibilidad REALES de esta sucursal — verificados contra
  // fotos reales del menú de cada una, distintos de verdad entre sucursales
  // (branch_products), no el precio plano de `products` (catálogo maestro
  // de nombres/categorías compartido, ya no la fuente de precio/verdad).
  const resolved = await resolveBranchOrderItems(
    supabase,
    branch.id,
    payload.items.map((item) => ({
      product_id: item.product_id,
      product_name: item.product_name,
      // La resolución solo necesita identidad; los callers web antiguos usan
      // quantity y se conserva abajo desde el payload original.
      requested_quantity: Number.isInteger(item.requested_quantity)
        ? item.requested_quantity as number
        : 1,
      tortilla: item.tortilla,
    })),
  );

  const orderItems: {
    id: string;
    name: string;
    price: number;
    quantity: number;
    tortilla?: TortillaChoice;
  }[] = [];
  let total = 0;
  let containsAlcohol = false;

  for (const [index, inputItem] of payload.items.entries()) {
    const canonicalItem = resolved.items[index];
    const product = resolved.products.find((candidate) =>
      candidate.id === canonicalItem.product_id
    )!;
    const requiresAdult = product.requires_adult_confirmation === true;
    if (requiresAdult) containsAlcohol = true;
    if (
      requiresAdult &&
      (payload.source === "voice" || payload.source === "whatsapp") &&
      payload.adult_confirmed !== true
    ) {
      throw new OrderValidationError(
        `Antes de crear el pedido con ${product.name}, confirma de forma explícita que quien recibe el pedido es mayor de edad.`,
      );
    }
    const requestedPieces = Number.isInteger(inputItem.requested_quantity);
    const item = buildOrderQuoteFromProducts(
      [{
        product_id: canonicalItem.product_id,
        product_name: canonicalItem.product_name,
        requested_quantity: (requestedPieces
          ? inputItem.requested_quantity
          : inputItem.quantity) as number,
        tortilla: inputItem.tortilla,
      }],
      [{
        id: product.id,
        name: product.name,
        price: product.price,
        // quantity ya representa unidades del catálogo, no piezas.
        pack_size: requestedPieces ? product.pack_size : null,
        requires_adult_confirmation: requiresAdult,
      }],
      {
        adult_confirmed: payload.adult_confirmed ||
          (!requestedPieces && payload.source !== "voice" &&
            payload.source !== "whatsapp"),
      },
    ).items[0];
    if (!Number.isInteger(item.quantity) || item.quantity <= 0) {
      throw new OrderValidationError(
        `Cantidad inválida para ${product.name}`,
      );
    }
    const lineTotal = Math.round(product.price * item.quantity * 100) / 100;
    total = Math.round((total + lineTotal) * 100) / 100;
    orderItems.push({
      id: product.id,
      name: product.name,
      price: product.price,
      quantity: item.quantity,
      ...(item.tortilla ? { tortilla: item.tortilla } : {}),
    });
  }

  return { payload, branch, orderItems, total, containsAlcohol };
}

export async function createOrderCore(
  supabase: any,
  rawPayload: CreateOrderPayload,
) {
  const { payload, branch, orderItems, total, containsAlcohol } =
    await prepareCreateOrder(supabase, rawPayload);

  // Customer memory: ensure identity before inserting the order. The database
  // increments order_count only if the idempotent insert actually creates a row.
  const customer = await upsertCustomer(
    supabase,
    branch.restaurant_id,
    payload.customer_phone,
    payload.customer_name,
    payload.customer_address,
  );

  // Bug crítico real confirmado en la auditoría del 3-sep-2026 ("haz múltiples
  // pruebas... rómpelo"): cuando un mensaje del cliente confundía al LLM
  // (input agresivo, fuera de tema, o simplemente "¿ya quedó mi pedido?"), el
  // loop de tool-use de WhatsApp se quedaba sin turnos disponibles DESPUÉS de
  // que crear_pedido ya había tenido éxito, y el fallback genérico
  // ("se me complicó procesar tu pedido") hacía que el cliente insistiera —
  // el siguiente mensaje disparaba una SEGUNDA llamada real a crear_pedido
  // con los mismos productos, creando un pedido duplicado real en `orders`
  // (verificado: 2 filas reales, mismo teléfono/sucursal/items/total,
  // segundos de diferencia). Se corrige el mensaje de fallback engañoso en
  // whatsapp-agent-core.ts, PERO la protección real y a prueba de canal
  // (voz, WhatsApp, web, cualquiera futuro) vive aquí: si ya existe un
  // pedido "pending" MUY reciente (mismo teléfono, misma sucursal, mismos
  // items exactos), se devuelve ESE pedido en vez de insertar uno nuevo —
  // nunca dos filas reales por una sola intención real de pedido.
  const itemsOrdenados = [...orderItems].sort((a, b) =>
    JSON.stringify(a).localeCompare(JSON.stringify(b))
  );
  const complementNotes = buildComplementNotes(
    payload.notes,
    [...new Set(payload.requested_complements ?? [])].sort(),
    [...new Set(payload.omit_default_complements ?? [])].sort(),
  );
  const finalNotes = containsAlcohol
    ? [
      complementNotes,
      "Recepción de alcohol: mayoría de edad confirmada por el cliente.",
    ].join("\n")
    : complementNotes;
  const dedupeFingerprint = await sha256Hex(
    JSON.stringify({
      restaurant_id: branch.restaurant_id,
      branch_id: branch.id,
      customer_name: payload.customer_name,
      customer_phone: payload.customer_phone,
      customer_address: payload.customer_address ?? null,
      payment_method: payload.payment_method ?? null,
      source: payload.source ?? "web",
      notes: finalNotes,
      total,
      items: itemsOrdenados.map((item) => ({
        id: item.id,
        name: item.name,
        price: item.price,
        quantity: item.quantity,
        tortilla: item.tortilla ?? null,
      })),
      requested_complements: [...(payload.requested_complements ?? [])].sort(),
      omit_default_complements: [...(payload.omit_default_complements ?? [])]
        .sort(),
    }),
  );
  const idempotencyKey = payload.idempotency_key
    ? await sha256Hex(`${branch.restaurant_id}:${payload.idempotency_key}`)
    : null;

  const { data: order, error: insertError } = await supabase.rpc(
    "create_order_idempotent",
    {
      p_order: {
        customer_name: payload.customer_name,
        customer_phone: payload.customer_phone,
        customer_address: payload.customer_address ?? null,
        customer_id: customer.id,
        restaurant_id: branch.restaurant_id,
        branch: branch.name,
        branch_id: branch.id,
        total,
        status: "pending",
        items: orderItems,
        source: payload.source ?? "web",
        call_transcript: payload.call_transcript ?? null,
        call_recording_url: payload.call_recording_url ?? null,
        notes: finalNotes,
        payment_method: payload.payment_method ?? null,
      },
      p_dedupe_fingerprint: dedupeFingerprint,
      p_idempotency_key: idempotencyKey,
    },
  );

  if (insertError?.code === "PT409") {
    throw new OrderConflictError(
      "Este intento de pedido ya fue procesado con datos diferentes. Revisa el pedido existente antes de crear otro.",
    );
  }
  if (insertError) throw insertError;

  return order;
}

async function upsertCustomer(
  supabase: any,
  restaurantId: string,
  phone: string,
  name: string,
  address?: string,
) {
  const { data: existing, error: lookupError } = await supabase
    .from("customers")
    .select("id, name")
    .eq("restaurant_id", restaurantId)
    .eq("phone", phone)
    .maybeSingle();
  if (lookupError) throw lookupError;

  let customer;
  if (existing) {
    const { data: updated, error } = await supabase
      .from("customers")
      .update({
        name: existing.name ?? name, // never overwrite a known name with a possibly-misheard one
      })
      .eq("id", existing.id)
      .select()
      .single();
    if (error) throw error;
    customer = updated;
  } else {
    const { data: created, error } = await supabase
      .from("customers")
      .insert({ restaurant_id: restaurantId, phone, name, order_count: 0 })
      .select()
      .single();
    if (error) {
      // Dos pedidos reales casi simultáneos del mismo cliente nuevo (ej.
      // manda el mensaje dos veces seguidas por mala señal) pueden ambos
      // ver "no existe" y ambos intentar el INSERT — el UNIQUE real
      // (restaurant_id, phone) hace que el segundo truene con 23505 en vez
      // de crear un duplicado silencioso (correcto), pero antes eso se
      // propagaba como error genérico al cliente en vez de recuperarse.
      // Verificado con pruebas de carga concurrente el 3-sep-2026.
      if (error.code === "23505") {
        const { data: existingRace, error: raceError } = await supabase
          .from("customers")
          .select("id, name")
          .eq("restaurant_id", restaurantId)
          .eq("phone", phone)
          .single();
        if (raceError) throw raceError;
        if (existingRace) {
          const { data: updated, error: updateError } = await supabase
            .from("customers")
            .update({
              name: existingRace.name ?? name,
            })
            .eq("id", existingRace.id)
            .select()
            .single();
          if (updateError) throw updateError;
          customer = updated;
        } else {
          throw error;
        }
      } else {
        throw error;
      }
    } else {
      customer = created;
    }
  }

  if (address) {
    const { count: addressCount, error: countError } = await supabase
      .from("customer_addresses")
      .select("id", { count: "exact", head: true })
      .eq("customer_id", customer.id);
    if (countError) throw countError;
    if (typeof addressCount !== "number") {
      throw new Error("No se pudo consultar las direcciones del cliente");
    }

    const { error: addressError } = await supabase
      .from("customer_addresses")
      .upsert(
        { customer_id: customer.id, address, is_default: addressCount === 0 },
        { onConflict: "customer_id,address", ignoreDuplicates: true },
      );
    if (addressError) throw addressError;
  }

  return customer;
}

export type CustomerTier = "BLACK" | "PLATINUM" | "GOLD" | "BLUE";

// Nota lista para inyectar tal cual en un prompt/tool-result: cuando el
// cliente es BLACK o PLATINUM el agente (voz o WhatsApp) debe saberlo y
// tratarlo con calidez extra/prioridad — pedido explícito de Javier, no
// dejar el tier calculado sin usar en el trato real.
export function vipNote(tier: CustomerTier | null): string | null {
  if (tier === "BLACK") {
    return "Es cliente BLACK — uno de los clientes de mayor consumo/frecuencia del restaurante (top 10%). Trátalo con calidez extra y dale prioridad.";
  }
  if (tier === "PLATINUM") {
    return "Es cliente PLATINUM — uno de los clientes más frecuentes/de mayor consumo del restaurante. Trátalo con calidez extra y dale prioridad.";
  }
  return null;
}

export function isOrderEligibleForRecommendations(status: unknown): boolean {
  return typeof status === "string" && [
    "pending",
    "preparando",
    "en_camino",
    "entregado",
    "completado",
  ].includes(status);
}

// Used by the voice agent's buscar_cliente Server Tool and by the WhatsApp
// webhook to greet a returning customer by name and offer their saved address
// before taking the order, per the requested flow: identify -> confirm/offer
// address -> take order -> recap what's included -> total -> wait time.
//
// Memoria real de cliente frecuente (no solo del último pedido): además del
// último pedido, agrega frequent_items (los productos más pedidos across
// TODO su historial real, contando cantidades reales de orders.items) y
// tier (BLACK/PLATINUM/GOLD/BLUE, mismos cortes de percentil que
// ClientesSection.tsx) calculado server-side vía la función SQL
// calc_customer_tier (ver supabase/migrations/20260903140000_customer_tier_percentile.sql)
// contra la distribución real de TODOS los clientes del restaurante, sin
// traer esa lista completa a este edge function.
export async function lookupCustomer(
  supabase: any,
  restaurantId: string,
  phone: string,
) {
  const { data: customer } = await supabase
    .from("customers")
    .select("id, name, order_count")
    .eq("restaurant_id", restaurantId)
    .eq("phone", normalizePhone(phone))
    .maybeSingle();

  if (!customer) {
    return { is_new: true as const };
  }

  const { data: addresses } = await supabase
    .from("customer_addresses")
    .select("address, label, is_default")
    .eq("customer_id", customer.id)
    .order("is_default", { ascending: false });

  // Todo el historial real de pedidos del cliente (no solo el último) —
  // ordenado desc, así allOrders[0] es también el último pedido y no hace
  // falta una segunda consulta aparte para eso.
  const { data: orderHistory } = await supabase
    .from("orders")
    .select("items, created_at, status")
    .eq("customer_id", customer.id)
    .order("created_at", { ascending: false });

  // Nunca sugerir como "lo de siempre" un pedido cancelado o con problema.
  // El filtro vuelve a aplicarse en memoria aunque en el futuro cambie la
  // consulta, para que esta regla de atención no dependa del LLM.
  const allOrders = (orderHistory ?? []).filter((order: any) =>
    isOrderEligibleForRecommendations(order.status)
  );
  const lastOrder = allOrders?.[0] ?? null;

  // frequent_items: ocurrencias reales (suma de cantidades) por producto,
  // contadas across TODO el historial real de orders.items de este
  // customer_id — no solo el último pedido. Con un solo pedido, coincide
  // con last_order_items (esperado).
  const conteoPorProducto = new Map<
    string,
    { name: string; quantity: number }
  >();
  for (const order of allOrders ?? []) {
    for (
      const item of (order.items ?? []) as {
        id?: string;
        name: string;
        quantity: number;
      }[]
    ) {
      const key = item.id ?? item.name;
      const actual = conteoPorProducto.get(key);
      if (actual) actual.quantity += item.quantity;
      else {
        conteoPorProducto.set(key, {
          name: item.name,
          quantity: item.quantity,
        });
      }
    }
  }
  const frequent_items = [...conteoPorProducto.values()]
    .sort((a, b) => b.quantity - a.quantity)
    .slice(0, 3);

  // Tier real por percentil, calculado en SQL (ver calc_customer_tier) —
  // si la función todavía no existe en la base (migración bloqueada por
  // Auto Mode, pendiente de aplicar a mano) o falla por cualquier motivo,
  // cae a tier: null en vez de romper la conversación.
  let tier: CustomerTier | null = null;
  const { data: tierResult, error: tierError } = await supabase.rpc(
    "calc_customer_tier",
    {
      p_restaurant_id: restaurantId,
      p_customer_id: customer.id,
    },
  );
  if (tierError) {
    console.error(
      "calc_customer_tier: no se pudo calcular, tier=null:",
      tierError,
    );
  } else {
    tier = (tierResult?.tier ?? null) as CustomerTier | null;
  }

  return {
    is_new: false as const,
    name: customer.name as string | null,
    order_count: customer.order_count as number,
    addresses: (addresses ?? []) as {
      address: string;
      label: string | null;
      is_default: boolean;
    }[],
    last_order_items: (lastOrder?.items ?? null) as
      | {
        name: string;
        quantity: number;
      }[]
      | null,
    frequent_items: frequent_items as { name: string; quantity: number }[],
    tier,
  };
}
