// Shared by supabase/functions/create-order (HTTP webhook, used by the website
// checkout and by the ElevenLabs voice agent's Server Tool) and by
// supabase/functions/whatsapp-webhook (called in-process, no HTTP round-trip,
// from the WhatsApp tool-use loop). Keeping this in one place means the price
// re-validation logic can't drift between the three callers.

// deno-lint-ignore-file no-explicit-any
export interface OrderItemInput {
  product_id: string
  quantity: number
}

export interface CreateOrderPayload {
  branch_slug?: string
  branch_name?: string
  customer_name: string
  customer_phone: string
  customer_address?: string
  items: OrderItemInput[]
  source?: "web" | "voice" | "whatsapp" | "admin"
  call_transcript?: string
  call_recording_url?: string
  // Instrucciones especiales del cliente ("sin cebolla", "tocar el
  // timbre") — antes se reconocían y repetían en el chat pero nunca
  // llegaban a cocina porque `orders` no tenía dónde guardarlas.
  notes?: string
  // Pedido real de Javier el 4-sep-2026: el agente (voz y WhatsApp) SIEMPRE
  // pregunta "efectivo o tarjeta" antes de crear el pedido (paso 6/7 del
  // flujo real), pero esa respuesta nunca se guardaba en ningún lado —
  // Historial de Órdenes no tenía nada real que mostrar como forma de pago.
  payment_method?: "efectivo" | "tarjeta"
  // Stable retry key generated by the caller for one checkout intent. It is
  // hashed before persistence and never treated as an authorization token.
  idempotency_key?: string
}

export class OrderValidationError extends Error {}

async function sha256Hex(value: string): Promise<string> {
  const bytes = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(value),
  )
  return Array.from(new Uint8Array(bytes))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("")
}

function invalidOptionalString(value: unknown, maxLength: number): boolean {
  return value !== undefined &&
    value !== null &&
    (typeof value !== "string" || value.length > maxLength)
}

// El mismo cliente real llega con el teléfono en formatos distintos según el
// canal: ElevenLabs transcribe lo que dice en voz (con o sin espacios/guiones,
// a veces sin el "52" de México), Meta manda el wa_id de WhatsApp sin "+" y a
// veces con un "1" extra después del "52" (quirk real y documentado de la
// Cloud API para números mexicanos migrados de la app clásica de WhatsApp), y
// el checkout web puede mandar cualquier formato que el cliente haya tecleado.
// Un match exacto (`.eq("phone", phone)`) sin normalizar hacía que el MISMO
// cliente real apareciera como "nuevo" cada vez que el formato variaba
// levemente — perdiendo en silencio su tier VIP, direcciones guardadas e
// historial, y creando un customer_id duplicado en vez de reconocerlo.
// Confirmado en vivo el 3-sep-2026 (auditoría multi-agente): dos filas reales
// de `customers` para la misma persona, cada una con order_count=1.
//
// Normaliza a los últimos 10 dígitos (número nacional significativo
// mexicano) — absorbe "+", espacios, guiones, "52"/"521" de país, y es
// estable sin importar cuál de los formatos reales llegue primero.
//
// Bug real encontrado en la auditoría adversarial del 3-sep-2026: la
// versión original devolvía soloDigitos SIN mínimo de longitud — un
// identificador sin dígitos reales (ej. un phone de prueba "widget-<texto
// sin números>") se reducía a "" (string vacío), y CUALQUIER otra
// conversación cuyo identificador tampoco tuviera dígitos colapsaba en el
// MISMO customer_id vacío — mezclando historial/order_count entre clientes
// que no tienen nada que ver. Confirmado en la base real: dos customers
// distintos con phone "" y "01". Fix: exigir un mínimo real de dígitos (7,
// el mínimo plausible de un teléfono real) antes de normalizar — si no se
// alcanza, se usa el string original completo (no el fragmento de dígitos)
// para no perder la unicidad de identificadores no numéricos.
export function normalizePhone(phone: string): string {
  const soloDigitos = phone.replace(/\D/g, "")
  if (soloDigitos.length >= 7) return soloDigitos.slice(-10)
  return phone.trim()
}

// Hallazgo real de la auditoría adversarial (3-sep-2026): el agente le dijo
// a un cliente de prueba "no procesamos ni guardamos los datos que
// compartiste por chat" al mandar un número de tarjeta completo — pero el
// mensaje se guardaba tal cual, número/vencimiento/CVV incluidos, en texto
// plano en whatsapp_conversations.messages. La afirmación del agente era
// falsa. Este helper redacta patrones de tarjeta/CVV/vencimiento ANTES de
// guardar cualquier mensaje real del cliente, para que esa afirmación sea
// cierta de verdad — se llama desde whatsapp-webhook y whatsapp-widget-chat
// justo antes de hacer push del mensaje del usuario al historial.
export function redactSensitiveInfo(text: string): string {
  return (
    text
      // Número de tarjeta: 13-19 dígitos, con o sin espacios/guiones entre grupos.
      .replace(/\b(?:\d[ -]?){13,19}\b/g, "[tarjeta oculta]")
      // CVV/CVC explícito con etiqueta.
      .replace(/\b(?:cvv|cvc|c\.?v\.?v\.?)\s*:?\s*\d{3,4}\b/gi, "[cvv oculto]")
      // Vencimiento tipo MM/YY o MM/YYYY, normalmente junto a "exp"/"vencimiento" en el mismo mensaje.
      .replace(/\b\d{1,2}\/\d{2,4}\b/g, "[vencimiento oculto]")
  )
}

// Bug real confirmado el 3-sep-2026 (auditoría de voz, 9 agentes): "cerveza
// Sol" y "coctel Margarita" devolvían CERO resultados pese a que "Sol" y
// "Margarita" sí están disponibles — el match es AND de todos los tokens
// contra products.name, y "cerveza"/"coctel" nunca aparecen literalmente en
// el nombre real (los productos se llaman "Sol", "Indio", "Margarita", no
// "Cerveza Sol"). El agente terminó diciéndole al cliente que no había
// cervezas ni cócteles disponibles, siendo falso — se sumaron estas palabras
// de categoría a las stopwords, igual que ya se hace con conectores, para
// que solo el nombre real de la bebida entre al match.
const STOPWORDS_BUSQUEDA = new Set([
  "de",
  "del",
  "la",
  "el",
  "los",
  "las",
  "un",
  "una",
  "unos",
  "unas",
  "y",
  "con",
  "para",
  "al",
  "cerveza",
  "cervezas",
  "coctel",
  "cocteles",
  "cóctel",
  "cócteles",
])

// Tokenizador compartido de buscar_producto (voz vía buscar-producto/index.ts
// y WhatsApp vía whatsapp-agent-core.ts) — antes cada canal tenía su propia
// copia duplicada de esta lógica (riesgo real de que un fix se aplicara a
// un canal y no al otro, señalado en la auditoría del 3-sep-2026).
//
// Dos gaps reales encontrados DESPUÉS de la tokenización básica, verificando
// en vivo con curl: (1) "tacos al pastor" (plural, como diría un cliente
// real) no encontraba "Taco Al Pastor (individual)" — el catálogo mezcla
// nombres en singular y en plural, y el ILIKE exacto de "tacos" no es
// substring de "Taco"; (2) "500g"/"1kg" (pegado, sin espacio, como lo
// escribiría el modelo o un cliente) no encontraba "Arrachera — 500 g" —
// el nombre real SIEMPRE lleva espacio antes de la unidad.
export function tokenizeForProductSearch(query: string): string[] {
  // Bug real encontrado el 3-sep-2026 (pruebas de "vida cotidiana"): un
  // cliente real dice "un kilo de bistec" o "medio kilo de arrachera" — la
  // palabra "kilo" nunca aparece en el nombre real del producto (que dice
  // "1 kg" o "500 g", nunca "kilo"), así que el token "kilo" no hacía match
  // con nada y el agente decía (falso) que el producto no existía, aunque
  // sí estaba disponible. Se normalizan las frases reales de kilos ANTES
  // de tokenizar, a la forma pegada que ya sabe resolver el bloque de abajo
  // (igual que "500g"/"1kg").
  const normalizada = query
    .toLowerCase()
    .replace(/tres\s+cuartos?\s+de\s+kilo/g, "750g")
    .replace(/cuarto\s+de\s+kilo/g, "250g")
    .replace(/medio\s+kilo/g, "500g")
    .replace(/\bkilos?\b/g, "kg")

  const raw = normalizada
    .split(/\s+/)
    .filter((t) => t.length > 1 && !STOPWORDS_BUSQUEDA.has(t))

  const tokens: string[] = []
  for (const t of raw) {
    const pesoMatch = t.match(/^(\d+)(kg|gr|g)$/)
    if (pesoMatch) {
      // separa el número de la unidad — así hace match sin importar si el
      // nombre real trae espacio entre ellos o no.
      tokens.push(pesoMatch[1], pesoMatch[2] === "gr" ? "g" : pesoMatch[2])
      continue
    }
    // singulariza un plural regular simple (tacos -> taco) — de sobra para
    // encontrar más, nunca para encontrar menos: un token más corto es un
    // substring MÁS permisivo, nunca más estricto.
    tokens.push(t.length > 4 && t.endsWith("s") ? t.slice(0, -1) : t)
  }
  return tokens.length > 0 ? tokens : [query.toLowerCase()]
}

export interface ProductoEncontrado {
  id: string
  name: string
  price: number
  /**
   * Cantidad fija de piezas del paquete si el producto se vende como
   * paquete indivisible (ej. 3 para "Tacos de Bistec de Res (orden de 3)"),
   * 1 si se vende por pieza individual ("... (individual)" / "Orden
   * individual" en su description), o null si no aplica esa noción de
   * "piezas por paquete" (bebidas, platillos completos, kilos, etc.).
   * Se calcula del name+description real en vez de dejar que el LLM tenga
   * que inferirlo de un paréntesis en el texto — bug real confirmado
   * 4-sep-2026: el agente de voz aceptó "un taco de bistec" sin corregir
   * al cliente pese a que el prompt ya le decía que revisara el nombre;
   * un campo estructurado explícito es más difícil de pasar por alto que
   * un patrón de texto libre.
   */
  pack_size: number | null
}

function extraerPackSize(
  name: string,
  description: string | null,
): number | null {
  const texto = `${name} ${description ?? ""}`
  const orden = texto.match(/orden de (\d+)/i)
  if (orden) return parseInt(orden[1], 10)
  if (/individual/i.test(texto)) return 1
  return null
}

/**
 * Búsqueda real de productos disponibles en una sucursal, compartida por el
 * agente de voz (buscar-producto/index.ts) y el de WhatsApp
 * (whatsapp-agent-core.ts) — antes cada uno traía su propia copia de esta
 * consulta (mismo texto, dos archivos) y las dos comparaban el query del
 * cliente SOLO contra `products.name`. Bug real confirmado 4-sep-2026: un
 * cliente pidió "una pizza" y el agente dijo que no había disponible, pese a
 * que sí existe un producto real ("Quesobich de Queso", categoría "Pizza
 * Quesobich") que es literalmente una pizza — la palabra "pizza" solo vive en
 * su `description` y en el nombre de su categoría, nunca en `products.name`,
 * así que la búsqueda angosta no lo encontraba. Ahora un token hace match si
 * aparece en el name, la description, la categoría, O cualquier alias de
 * `products.search_keywords` (columna sembrada a mano para ~250 productos
 * reales el 4-sep-2026) — todos los tokens siguen siendo obligatorios (AND),
 * solo se amplió EN QUÉ campo puede aparecer cada uno.
 */
export async function buscarProductosCore(
  supabase: any,
  {
    branchId,
    restaurantId,
    query,
  }: {
    branchId: string
    restaurantId: string
    query: string
  },
): Promise<ProductoEncontrado[]> {
  const tokens = tokenizeForProductSearch(query)

  const { data: rows, error } = await supabase
    .from("branch_products")
    .select(
      "price, is_available, products!inner(id, name, description, restaurant_id, search_keywords, categories(name))",
    )
    .eq("branch_id", branchId)
    .eq("is_available", true)
    .eq("products.restaurant_id", restaurantId)
    .limit(400)
  if (error) throw error

  const coincide = (r: any) => {
    const producto = r.products
    const textoPlano = [
      producto.name,
      producto.description,
      producto.categories?.name,
    ]
      .filter(Boolean)
      .join(" ")
      .toLowerCase()
    const alias: string[] = producto.search_keywords ?? []
    return tokens.every(
      (t) =>
        textoPlano.includes(t) ||
        alias.some((a) => a.toLowerCase().includes(t)),
    )
  }

  return (rows ?? [])
    .filter(coincide)
    .slice(0, 8)
    .map((r: any) => ({
      id: r.products.id,
      name: r.products.name,
      price: r.price,
      pack_size: extraerPackSize(r.products.name, r.products.description),
    }))
}

export async function createOrderCore(
  supabase: any,
  payload: CreateOrderPayload,
) {
  if (!payload || typeof payload !== "object") {
    throw new OrderValidationError("Payload inválido")
  }
  if (
    (!payload.branch_slug && !payload.branch_name) ||
    !payload.customer_name ||
    !payload.customer_phone
  ) {
    throw new OrderValidationError(
      "branch_slug (o branch_name), customer_name y customer_phone son requeridos",
    )
  }
  if (
    typeof payload.customer_name !== "string" ||
    payload.customer_name.trim().length > 160 ||
    typeof payload.customer_phone !== "string" ||
    payload.customer_phone.length > 64 ||
    invalidOptionalString(payload.customer_address, 1000) ||
    invalidOptionalString(payload.notes, 2000) ||
    invalidOptionalString(payload.call_transcript, 20000) ||
    invalidOptionalString(payload.call_recording_url, 2000)
  ) {
    throw new OrderValidationError(
      "Uno o más campos exceden el tamaño permitido",
    )
  }
  payload = {
    ...payload,
    customer_phone: normalizePhone(payload.customer_phone),
  }
  if (!Array.isArray(payload.items) || payload.items.length === 0) {
    throw new OrderValidationError("El pedido no tiene productos")
  }
  if (
    payload.items.length > 100 ||
    payload.items.some(
      (item) =>
        !item ||
        typeof item.product_id !== "string" ||
        item.product_id.length > 64 ||
        !Number.isInteger(item.quantity) ||
        item.quantity < 1 ||
        item.quantity > 100,
    )
  ) {
    throw new OrderValidationError("Productos o cantidades inválidos")
  }

  const branchQuery = supabase
    .from("branches")
    .select("id, name, is_active, restaurant_id")
  const { data: branch, error: branchError } = await (
    payload.branch_slug
      ? branchQuery.eq("slug", payload.branch_slug)
      : branchQuery.eq("name", payload.branch_name)
  ).maybeSingle()

  if (branchError) throw branchError
  if (!branch || !branch.is_active) {
    throw new OrderValidationError(
      `Sucursal '${
        payload.branch_slug ?? payload.branch_name
      }' no encontrada o inactiva`,
    )
  }

  // Precio y disponibilidad REALES de esta sucursal — verificados contra
  // fotos reales del menú de cada una, distintos de verdad entre sucursales
  // (branch_products), no el precio plano de `products` (catálogo maestro
  // de nombres/categorías compartido, ya no la fuente de precio/verdad).
  const productIds = payload.items.map((i) => i.product_id)
  const { data: branchProducts, error: productsError } = await supabase
    .from("branch_products")
    .select("price, is_available, products!inner(id, name)")
    .eq("branch_id", branch.id)
    .in("product_id", productIds)

  if (productsError) throw productsError

  const orderItems: {
    id: string
    name: string
    price: number
    quantity: number
  }[] = []
  let total = 0

  for (const item of payload.items) {
    const bp = branchProducts?.find(
      (r: any) => r.products.id === item.product_id,
    )
    if (!bp || !bp.is_available) {
      throw new OrderValidationError(
        `Producto no disponible: ${item.product_id}`,
      )
    }
    if (!Number.isInteger(item.quantity) || item.quantity <= 0) {
      throw new OrderValidationError(
        `Cantidad inválida para ${bp.products.name}`,
      )
    }
    const lineTotal = Number(bp.price) * item.quantity
    total += lineTotal
    orderItems.push({
      id: bp.products.id,
      name: bp.products.name,
      price: Number(bp.price),
      quantity: item.quantity,
    })
  }

  // Customer memory: ensure identity before inserting the order. The database
  // increments order_count only if the idempotent insert actually creates a row.
  const customer = await upsertCustomer(
    supabase,
    branch.restaurant_id,
    payload.customer_phone,
    payload.customer_name,
    payload.customer_address,
  )

  // Bug crítico real confirmado en la auditoría del 3-sep-2026 ("haz múltiples
  // pruebas... rómpelo"): cuando un mensaje del cliente confundía al LLM
  // (input agresivo, fuera de tema, o simplemente "¿ya quedó mi pedido?"), el
  // loop de tool-use de WhatsApp se quedaba sin turnos disponibles DESPUÉS de
  // que crear_pedido ya había tenido éxito, y el fallback genérico
  // ("se me complicó procesar tu pedido") hacía que el cliente insistiera —
  // el siguiente mensaje disparaba una SEGUNDA llamada real a crear_pedido
  // con los mismos productos, creando un pedido duplicado real en `orders`
  // (verificado: 2 filas reales, mismo teléfono/sucursal/items/total,
  // segundos de diferencia). Se corrige el mensaje de fallback engañoso en
  // whatsapp-agent-core.ts, PERO la protección real y a prueba de canal
  // (voz, WhatsApp, web, cualquiera futuro) vive aquí: si ya existe un
  // pedido "pending" MUY reciente (mismo teléfono, misma sucursal, mismos
  // items exactos), se devuelve ESE pedido en vez de insertar uno nuevo —
  // nunca dos filas reales por una sola intención real de pedido.
  const itemsOrdenados = [...orderItems].sort((a, b) =>
    a.id.localeCompare(b.id),
  )
  const dedupeFingerprint = await sha256Hex(
    JSON.stringify({
      restaurant_id: branch.restaurant_id,
      branch_id: branch.id,
      customer_phone: payload.customer_phone,
      items: itemsOrdenados.map((item) => ({
        id: item.id,
        quantity: item.quantity,
      })),
    }),
  )
  if (
    payload.idempotency_key &&
    (typeof payload.idempotency_key !== "string" ||
      payload.idempotency_key.length > 200)
  ) {
    throw new OrderValidationError("idempotency_key inválido")
  }
  const idempotencyKey = payload.idempotency_key
    ? await sha256Hex(`${branch.restaurant_id}:${payload.idempotency_key}`)
    : null

  const { data: order, error: insertError } = await supabase.rpc(
    "create_order_idempotent",
    {
      p_order: {
        customer_name: payload.customer_name,
        customer_phone: payload.customer_phone,
        customer_address: payload.customer_address ?? null,
        customer_id: customer.id,
        restaurant_id: branch.restaurant_id,
        branch: branch.name,
        branch_id: branch.id,
        total,
        status: "pending",
        items: orderItems,
        source: payload.source ?? "web",
        call_transcript: payload.call_transcript ?? null,
        call_recording_url: payload.call_recording_url ?? null,
        notes: payload.notes ?? null,
        payment_method: payload.payment_method ?? null,
      },
      p_dedupe_fingerprint: dedupeFingerprint,
      p_idempotency_key: idempotencyKey,
    },
  )

  if (insertError) throw insertError

  return order
}

async function upsertCustomer(
  supabase: any,
  restaurantId: string,
  phone: string,
  name: string,
  address?: string,
) {
  const { data: existing } = await supabase
    .from("customers")
    .select("id, name, order_count")
    .eq("restaurant_id", restaurantId)
    .eq("phone", phone)
    .maybeSingle()

  let customer
  if (existing) {
    const { data: updated, error } = await supabase
      .from("customers")
      .update({
        name: existing.name ?? name, // never overwrite a known name with a possibly-misheard one
        order_count: existing.order_count,
      })
      .eq("id", existing.id)
      .select()
      .single()
    if (error) throw error
    customer = updated
  } else {
    const { data: created, error } = await supabase
      .from("customers")
      .insert({ restaurant_id: restaurantId, phone, name, order_count: 0 })
      .select()
      .single()
    if (error) {
      // Dos pedidos reales casi simultáneos del mismo cliente nuevo (ej.
      // manda el mensaje dos veces seguidas por mala señal) pueden ambos
      // ver "no existe" y ambos intentar el INSERT — el UNIQUE real
      // (restaurant_id, phone) hace que el segundo truene con 23505 en vez
      // de crear un duplicado silencioso (correcto), pero antes eso se
      // propagaba como error genérico al cliente en vez de recuperarse.
      // Verificado con pruebas de carga concurrente el 3-sep-2026.
      if (error.code === "23505") {
        const { data: existingRace } = await supabase
          .from("customers")
          .select("id, name, order_count")
          .eq("restaurant_id", restaurantId)
          .eq("phone", phone)
          .single()
        if (existingRace) {
          const { data: updated, error: updateError } = await supabase
            .from("customers")
            .update({
              name: existingRace.name ?? name,
              order_count: existingRace.order_count,
            })
            .eq("id", existingRace.id)
            .select()
            .single()
          if (updateError) throw updateError
          customer = updated
        } else {
          throw error
        }
      } else {
        throw error
      }
    } else {
      customer = created
    }
  }

  if (address) {
    const { data: hasAnyAddress } = await supabase
      .from("customer_addresses")
      .select("id", { count: "exact", head: true })
      .eq("customer_id", customer.id)

    await supabase
      .from("customer_addresses")
      .upsert(
        { customer_id: customer.id, address, is_default: !hasAnyAddress },
        { onConflict: "customer_id,address", ignoreDuplicates: true },
      )
  }

  return customer
}

export type CustomerTier = "BLACK" | "PLATINUM" | "GOLD" | "BLUE"

// Nota lista para inyectar tal cual en un prompt/tool-result: cuando el
// cliente es BLACK o PLATINUM el agente (voz o WhatsApp) debe saberlo y
// tratarlo con calidez extra/prioridad — pedido explícito de Javier, no
// dejar el tier calculado sin usar en el trato real.
export function vipNote(tier: CustomerTier | null): string | null {
  if (tier === "BLACK") {
    return "Es cliente BLACK — uno de los clientes de mayor consumo/frecuencia del restaurante (top 10%). Trátalo con calidez extra y dale prioridad."
  }
  if (tier === "PLATINUM") {
    return "Es cliente PLATINUM — uno de los clientes más frecuentes/de mayor consumo del restaurante. Trátalo con calidez extra y dale prioridad."
  }
  return null
}

// Used by the voice agent's buscar_cliente Server Tool and by the WhatsApp
// webhook to greet a returning customer by name and offer their saved address
// before taking the order, per the requested flow: identify -> confirm/offer
// address -> take order -> recap what's included -> total -> wait time.
//
// Memoria real de cliente frecuente (no solo del último pedido): además del
// último pedido, agrega frequent_items (los productos más pedidos across
// TODO su historial real, contando cantidades reales de orders.items) y
// tier (BLACK/PLATINUM/GOLD/BLUE, mismos cortes de percentil que
// ClientesSection.tsx) calculado server-side vía la función SQL
// calc_customer_tier (ver supabase/migrations/20260903140000_customer_tier_percentile.sql)
// contra la distribución real de TODOS los clientes del restaurante, sin
// traer esa lista completa a este edge function.
export async function lookupCustomer(
  supabase: any,
  restaurantId: string,
  phone: string,
) {
  const { data: customer } = await supabase
    .from("customers")
    .select("id, name, order_count")
    .eq("restaurant_id", restaurantId)
    .eq("phone", normalizePhone(phone))
    .maybeSingle()

  if (!customer) {
    return { is_new: true as const }
  }

  const { data: addresses } = await supabase
    .from("customer_addresses")
    .select("address, label, is_default")
    .eq("customer_id", customer.id)
    .order("is_default", { ascending: false })

  // Todo el historial real de pedidos del cliente (no solo el último) —
  // ordenado desc, así allOrders[0] es también el último pedido y no hace
  // falta una segunda consulta aparte para eso.
  const { data: allOrders } = await supabase
    .from("orders")
    .select("items, created_at")
    .eq("customer_id", customer.id)
    .order("created_at", { ascending: false })

  const lastOrder = allOrders?.[0] ?? null

  // frequent_items: ocurrencias reales (suma de cantidades) por producto,
  // contadas across TODO el historial real de orders.items de este
  // customer_id — no solo el último pedido. Con un solo pedido, coincide
  // con last_order_items (esperado).
  const conteoPorProducto = new Map<
    string,
    { name: string; quantity: number }
  >()
  for (const order of allOrders ?? []) {
    for (const item of (order.items ?? []) as {
      id?: string
      name: string
      quantity: number
    }[]) {
      const key = item.id ?? item.name
      const actual = conteoPorProducto.get(key)
      if (actual) actual.quantity += item.quantity
      else {
        conteoPorProducto.set(key, {
          name: item.name,
          quantity: item.quantity,
        })
      }
    }
  }
  const frequent_items = [...conteoPorProducto.values()]
    .sort((a, b) => b.quantity - a.quantity)
    .slice(0, 3)

  // Tier real por percentil, calculado en SQL (ver calc_customer_tier) —
  // si la función todavía no existe en la base (migración bloqueada por
  // Auto Mode, pendiente de aplicar a mano) o falla por cualquier motivo,
  // cae a tier: null en vez de romper la conversación.
  let tier: CustomerTier | null = null
  const { data: tierResult, error: tierError } = await supabase.rpc(
    "calc_customer_tier",
    {
      p_restaurant_id: restaurantId,
      p_customer_id: customer.id,
    },
  )
  if (tierError) {
    console.error(
      "calc_customer_tier: no se pudo calcular, tier=null:",
      tierError,
    )
  } else {
    tier = (tierResult?.tier ?? null) as CustomerTier | null
  }

  return {
    is_new: false as const,
    name: customer.name as string | null,
    order_count: customer.order_count as number,
    addresses: (addresses ?? []) as {
      address: string
      label: string | null
      is_default: boolean
    }[],
    last_order_items: (lastOrder?.items ?? null) as
      | {
          name: string
          quantity: number
        }[]
      | null,
    frequent_items: frequent_items as { name: string; quantity: number }[],
    tier,
  }
}
