-- Real menu for Los Taquitos de PM, transcribed from the live site's
-- Fco. de Montejo branch menu (https://www.lostaquitosdepm.com/menufranciscodemontejo,
-- scraped + read via vision on 2026-09-02). Replaces/extends whatever placeholder
-- categories/products existed so the site and the voice agent quote real prices.
--
-- NOTE: if the products table already has placeholder/admin-entered rows, this
-- migration ADDS to them rather than replacing them (no unique constraint on
-- products.name to safely upsert on). Review/clean up duplicates after applying,
-- or truncate `products` first if you want a clean slate.

INSERT INTO public.categories (name, slug, display_order) VALUES
  ('Tacos', 'tacos', 1),
  ('Gringas', 'gringas', 2),
  ('Mestizas', 'mestizas', 3),
  ('Alambre', 'alambre', 4),
  ('Tacos Suizos', 'tacos-suizos', 5),
  ('Boyo-Hamburguesas', 'hamburguesas', 6),
  ('Chetacos', 'chetacos', 7),
  ('Papas de PM', 'papas', 8),
  ('Francés Suizo', 'frances-suizo', 9),
  ('Entradas', 'entradas', 10),
  ('Frijoles Charros', 'frijoles-charros', 11),
  ('Quesadillas', 'quesadillas', 12),
  ('Queso Fundido', 'queso-fundido', 13),
  ('Nachos', 'nachos', 14),
  ('Pizza Quesobich', 'pizza', 15),
  ('Platillos PM', 'platillos', 16),
  ('Kilos a Domicilio', 'kilos', 17),
  ('Postres', 'postres', 18),
  ('Refrescos', 'refrescos', 19),
  ('Aguas Frescas', 'aguas-frescas', 20),
  ('Cervezas', 'cervezas', 21),
  ('Licores y Cocktails', 'licores', 22),
  ('Guarniciones Extra', 'extras', 23)
ON CONFLICT (restaurant_id, slug) DO UPDATE
SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;

INSERT INTO public.products (category_id, name, description, price, is_popular, display_order) VALUES
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Taco Al Pastor (individual)', 'Orden individual', 42, true, 1),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Taco de Rajas (individual)', 'Orden individual', 37, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Taco de Champiñones (individual)', 'Orden individual', 38, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Tacos de Chorizo (orden de 3)', 'Orden de 3 tacos', 150, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Tacos de Bistec de Res (orden de 3)', 'Orden de 3 tacos', 194, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Tacos de Pechuga de Pollo (orden de 3)', 'Orden de 3 tacos', 184, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Tacos de Chuleta de Cerdo (orden de 3)', 'Orden de 3 tacos', 184, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Tacos de Costilla de Res (orden de 3)', 'Orden de 3 tacos', 189, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Tacos de Arrachera (orden de 3)', 'Orden de 3 tacos', 254, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Tacos de Poc-Chuc (orden de 3)', 'Orden de 3 tacos', 189, false, 10),
  ((SELECT id FROM public.categories WHERE slug = 'tacos'), 'Tacos de Bistec Encebollado (orden de 3)', 'Orden de 3 tacos', 202, false, 11),
  ((SELECT id FROM public.categories WHERE slug = 'gringas'), 'Gringa de Pastor', 'Orden de 2 tacos', 194, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'gringas'), 'Gringa de Bistec', 'Orden de 2 tacos', 224, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'gringas'), 'Gringa de Pechuga de Pollo', 'Orden de 2 tacos', 212, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'gringas'), 'Gringa de Chuleta', 'Orden de 2 tacos', 212, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'gringas'), 'Gringa de Costilla', 'Orden de 2 tacos', 217, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'gringas'), 'Gringa de Arrachera', 'Orden de 2 tacos', 299, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'gringas'), 'Gringa de Poc-Chuc', 'Orden de 2 tacos', 217, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'mestizas'), 'Mestiza de Pastor', 'Orden de 2 tacos', 168, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'mestizas'), 'Mestiza de Poc-Chuc', 'Orden de 2 tacos', 175, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'mestizas'), 'Mestiza de Bistec', 'Orden de 2 tacos', 194, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'mestizas'), 'Mestiza de Pechuga', 'Orden de 2 tacos', 184, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'mestizas'), 'Mestiza de Chuleta', 'Orden de 2 tacos', 184, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'mestizas'), 'Mestiza de Costilla', 'Orden de 2 tacos', 189, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'mestizas'), 'Mestiza de Arrachera', 'Orden de 2 tacos', 269, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'alambre'), 'Alambre de Pastor', 'Orden de 5 tacos', 276, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'alambre'), 'Alambre de Bistec', 'Orden de 5 tacos', 283, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'alambre'), 'Alambre de Pechuga', 'Orden de 5 tacos', 269, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'alambre'), 'Alambre de Chuleta', 'Orden de 5 tacos', 269, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'alambre'), 'Alambre de Costilla', 'Orden de 5 tacos', 276, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'alambre'), 'Alambre de Arrachera', 'Orden de 5 tacos', 343, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Pastor', 'Orden de 5 tacos', 247, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Bistec', 'Orden de 5 tacos', 291, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Chuleta', 'Orden de 5 tacos', 284, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Pechuga', 'Orden de 5 tacos', 284, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Costilla', 'Orden de 5 tacos', 284, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Arrachera', 'Orden de 5 tacos', 373, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Poc-Chuc', 'Orden de 5 tacos', 284, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Chorizo', 'Orden de 5 tacos', 209, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Suizo de Chile Poblano', 'Orden de 5 tacos', 204, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Alambre Suizo de Pastor', NULL, 306, false, 10),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Alambre Suizo de Bistec', NULL, 314, false, 11),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Alambre Suizo de Pechuga', NULL, 306, false, 12),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Alambre Suizo de Chuleta', NULL, 306, false, 13),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Alambre Suizo de Costilla', NULL, 306, false, 14),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Alambre Suizo de Arrachera', NULL, 371, false, 15),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Tacos Suizos de Chile Poblano y Bistec', NULL, 328, false, 16),
  ((SELECT id FROM public.categories WHERE slug = 'tacos-suizos'), 'Tacos Suizos de Chile Poblano y Arrachera', NULL, 378, false, 17),
  ((SELECT id FROM public.categories WHERE slug = 'hamburguesas'), 'Boyo-Hamburguesa Sencilla', NULL, 194, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'hamburguesas'), 'Boyo-Hamburguesa con Queso', NULL, 224, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'hamburguesas'), 'Boyo-Hamburguesa con Queso y Tocino', NULL, 238, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'chetacos'), 'Chetaco de Pastor', 'Tortilla de harina extra grande con frijol, queso, champiñones y carne; con ensalada de lechuga y tomate', 291, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'chetacos'), 'Chetaco de Champiñón', 'Tortilla de harina extra grande con frijol, queso, champiñones y carne; con ensalada de lechuga y tomate', 306, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'chetacos'), 'Chetaco de Bistec de Res', 'Tortilla de harina extra grande con frijol, queso, champiñones y carne; con ensalada de lechuga y tomate', 314, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'chetacos'), 'Chetaco de Chuleta de Cerdo', 'Tortilla de harina extra grande con frijol, queso, champiñones y carne; con ensalada de lechuga y tomate', 306, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'chetacos'), 'Chetaco de Pechuga', 'Tortilla de harina extra grande con frijol, queso, champiñones y carne; con ensalada de lechuga y tomate', 306, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'chetacos'), 'Chetaco de Costilla de Res', 'Tortilla de harina extra grande con frijol, queso, champiñones y carne; con ensalada de lechuga y tomate', 306, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'chetacos'), 'Chetaco de Poc-Chuc', 'Tortilla de harina extra grande con frijol, queso, champiñones y carne; con ensalada de lechuga y tomate', 306, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'chetacos'), 'Chetaco de Arrachera', 'Tortilla de harina extra grande con frijol, queso, champiñones y carne; con ensalada de lechuga y tomate', 373, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'papas'), 'Papa Tradicional', 'Papa rellena', 204, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'papas'), 'Papa Pastor', 'Papa rellena', 262, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'papas'), 'Papa Bistec', 'Papa rellena', 283, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'papas'), 'Papa Chuleta', 'Papa rellena', 276, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'papas'), 'Papa Pechuga', 'Papa rellena', 276, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'papas'), 'Papa Costilla', 'Papa rellena', 276, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'papas'), 'Papa Arrachera', 'Papa rellena', 352, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'frances-suizo'), 'Francés Suizo de Pastor', 'Francés tostadito con guacamole, frijol, queso gratinado y carne, hecho en horno', 262, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'frances-suizo'), 'Francés Suizo de Champiñón', 'Francés tostadito con guacamole, frijol, queso gratinado y carne, hecho en horno', 262, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'frances-suizo'), 'Francés Suizo de Bistec de Res', 'Francés tostadito con guacamole, frijol, queso gratinado y carne, hecho en horno', 283, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'frances-suizo'), 'Francés Suizo de Chuleta de Cerdo', 'Francés tostadito con guacamole, frijol, queso gratinado y carne, hecho en horno', 276, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'frances-suizo'), 'Francés Suizo de Pechuga', 'Francés tostadito con guacamole, frijol, queso gratinado y carne, hecho en horno', 276, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'frances-suizo'), 'Francés Suizo de Costilla de Res', 'Francés tostadito con guacamole, frijol, queso gratinado y carne, hecho en horno', 276, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'frances-suizo'), 'Francés Suizo de Poc-Chuc', 'Francés tostadito con guacamole, frijol, queso gratinado y carne, hecho en horno', 276, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'frances-suizo'), 'Francés Suizo de Arrachera', 'Francés tostadito con guacamole, frijol, queso gratinado y carne, hecho en horno', 352, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'entradas'), 'Frijol con Tostada', NULL, 93, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'entradas'), 'Guacamole', NULL, 142, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'entradas'), 'Carbolla', NULL, 106, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'entradas'), 'Cebollas Cambray', NULL, 135, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'entradas'), 'Chicharrón de Queso', NULL, 172, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'entradas'), 'Alitas de Pollo', NULL, 204, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'entradas'), 'Papas a la Francesa', NULL, 113, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'frijoles-charros'), 'Frijoles Charros Normal', NULL, 123, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'frijoles-charros'), 'Frijoles Charros Normal (1/2 orden)', NULL, 82, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'frijoles-charros'), 'Frijoles Charros con Queso', NULL, 142, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'frijoles-charros'), 'Frijoles Charros con Queso (1/2 orden)', NULL, 106, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'frijoles-charros'), 'Frijoles Charros Especiales', NULL, 178, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'frijoles-charros'), 'Frijoles Charros Especiales (1/2 orden)', NULL, 136, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'quesadillas'), 'Quesadilla de Natural', 'De maíz o harina', 109, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'quesadillas'), 'Quesadilla de Rajas', 'De maíz o harina', 124, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'quesadillas'), 'Quesadilla de Champiñones', 'De maíz o harina', 127, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'quesadillas'), 'Quesadilla de Chorizo', 'De maíz o harina', 135, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'queso-fundido'), 'Queso Fundido Natural', NULL, 160, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'queso-fundido'), 'Queso Fundido Rajas', NULL, 175, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'queso-fundido'), 'Queso Fundido Champiñones', NULL, 175, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'queso-fundido'), 'Queso Fundido Tocino', NULL, 179, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'queso-fundido'), 'Queso Fundido Chorizo', NULL, 179, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Pastor', NULL, 328, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Pastor (1/2 orden)', NULL, 232, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Champiñón', NULL, 320, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Champiñón (1/2 orden)', NULL, 232, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Bistec', NULL, 373, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Bistec (1/2 orden)', NULL, 262, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Pechuga', NULL, 363, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Pechuga (1/2 orden)', NULL, 249, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Chuleta', NULL, 358, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Chuleta (1/2 orden)', NULL, 249, false, 10),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Costilla', NULL, 367, false, 11),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Costilla (1/2 orden)', NULL, 255, false, 12),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Arrachera', NULL, 433, false, 13),
  ((SELECT id FROM public.categories WHERE slug = 'nachos'), 'Nachos de Arrachera (1/2 orden)', NULL, 299, false, 14),
  ((SELECT id FROM public.categories WHERE slug = 'pizza'), 'Quesobich de Queso', 'Pizza individual, orilla rellena de queso', 206, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'pizza'), 'Quesobich de Pastor', 'Pastor con piña', 232, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'pizza'), 'Quesobich de Bistec', NULL, 254, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'pizza'), 'Quesobich de Pollo', NULL, 247, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'pizza'), 'Quesobich de Chuleta de Cerdo', NULL, 247, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'pizza'), 'Quesobich de Costilla de Res', NULL, 247, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'pizza'), 'Quesobich de Arrachera', NULL, 291, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'pizza'), 'Quesobich Vegetariana', 'Champiñones, cebolla y rajas de chile poblano', 212, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Crujientes de Pechuga de Pollo', '* No incluye guarniciones estándar', 329, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Platillo de Pastor', NULL, 335, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Platillo de Bistec', NULL, 404, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Platillo de Pechuga de Pollo', NULL, 378, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Platillo de Chuleta de Cerdo', NULL, 378, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Platillo de Costilla de Res', NULL, 388, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Platillo de Arrachera', NULL, 492, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Platillo de Poc-Chuc', '* No incluye guarniciones estándar', 368, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Fajitas de Bistec', '* No incluye guarniciones estándar', 404, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Fajitas de Pechuga', '* No incluye guarniciones estándar', 393, false, 10),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Fajitas de Arrachera', '* No incluye guarniciones estándar', 492, false, 11),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Parrillada para 2', '* No incluye guarniciones estándar', 612, false, 12),
  ((SELECT id FROM public.categories WHERE slug = 'platillos'), 'Parrillada para 4', '* No incluye guarniciones estándar', 1045, false, 13),
  ((SELECT id FROM public.categories WHERE slug = 'postres'), 'Crema Española', NULL, 83, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'postres'), 'Crema de Coco', NULL, 83, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'postres'), 'Flan', NULL, 83, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'postres'), 'Queso Napolitano', 'Receta de la casa', 109, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Coca-Cola', 'Botella o lata', 53, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Coca-Cola Light', 'Botella o lata', 53, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Coca-Cola sin Azúcar', 'Botella o lata', 53, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Toronja Cristal', NULL, 53, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Fanta', 'Botella', 53, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Sprite', 'Lata', 53, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Sprite Cero', 'Lata', 53, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Sidral Mundet', 'Botella', 53, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Agua Mineral Cristal', '300ml', 53, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Agua Purificada', '600ml', 53, false, 10),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Topo Chico', '355ml', 74, false, 11),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Limonada', NULL, 60, false, 12),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Limonada con Soda', NULL, 73, false, 13),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Limonada con Topo Chico', NULL, 100, false, 14),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Naranjada', NULL, 60, false, 15),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Naranjada con Soda', NULL, 73, false, 16),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Naranjada con Topo Chico', NULL, 100, false, 17),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Suero con Soda', NULL, 79, false, 18),
  ((SELECT id FROM public.categories WHERE slug = 'refrescos'), 'Suero con Topo Chico', NULL, 95, false, 19),
  ((SELECT id FROM public.categories WHERE slug = 'aguas-frescas'), 'Agua de Jamaica', 'Rellenable una vez', 60, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'aguas-frescas'), 'Horchata', 'Rellenable una vez', 60, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'aguas-frescas'), 'Té', 'Rellenable una vez', 60, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Sol', NULL, 80, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Superior', NULL, 80, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Tecate Light', NULL, 80, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Heineken 0.0', NULL, 80, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Heineken', NULL, 90, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Heineken Silver', NULL, 90, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Indio', NULL, 80, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'XX Lager', NULL, 80, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'XX Ámbar', NULL, 80, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Amstel Ultra', NULL, 90, false, 10),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Bohemia Clara', NULL, 90, false, 11),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Bohemia Oscura', NULL, 90, false, 12),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Ceiba Dorada Premium', NULL, 120, false, 13),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Ceiba Light Lager', NULL, 120, false, 14),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Ceiba Mestiza', NULL, 120, false, 15),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Ceiba Stout', NULL, 120, false, 16),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Patito Oscura', NULL, 120, false, 17),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Patito Lager', NULL, 120, false, 18),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Ojo Rojo', NULL, 44, false, 19),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Vaso de Chelada', NULL, 22, false, 20),
  ((SELECT id FROM public.categories WHERE slug = 'cervezas'), 'Vaso de Michelada', NULL, 30, false, 21),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Ron Appleton Especial', NULL, 117, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Ron Bacardí Añejo', NULL, 113, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Ron Bacardí Blanco', NULL, 106, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Ron Bacardí Solera', NULL, 128, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Tequila Don Julio Reposado', NULL, 168, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Tequila Herradura Reposado', NULL, 139, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Tequila Jimador', NULL, 106, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Tequila Tradicional', NULL, 113, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Vodka Absolut', NULL, 123, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Vodka Smirnoff', NULL, 109, false, 10),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Whisky Buchanan''s', NULL, 178, false, 11),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Whisky Chivas Regal', NULL, 156, false, 12),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Whisky J.W. Etiqueta Negra', NULL, 190, false, 13),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Caribe Cooler', NULL, 110, false, 14),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Conga', NULL, 114, false, 15),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Conga sin Alcohol', NULL, 105, false, 16),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Daiquiri', NULL, 109, false, 17),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Daiquiri sin Alcohol', NULL, 96, false, 18),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Limonada Eléctrica', NULL, 109, false, 19),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Margarita', NULL, 109, false, 20),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Margarita sin Alcohol', NULL, 100, false, 21),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Piñada', NULL, 100, false, 22),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Piña Colada', NULL, 112, false, 23),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Sangría', NULL, 112, false, 24),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Sangría sin Alcohol', NULL, 100, false, 25),
  ((SELECT id FROM public.categories WHERE slug = 'licores'), 'Vino Tinto Selección (copa)', NULL, 102, false, 26),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Extra Champiñón', NULL, 35, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Extra Chile Poblano', NULL, 35, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Extra Chorizo', NULL, 36, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Extra Guacamole', NULL, 49, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Extra Rajas', NULL, 35, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Extra Tocino', NULL, 36, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Orden Tortilla de Harina', NULL, 24, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Orden Tortilla de Maíz', NULL, 22, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'extras'), 'Extra Queso', NULL, 52, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Pastor — 250 g', 'Kilo completo $900. Incluye salsa roja, salsa verde, limones y tortillas.', 225, false, 1),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Pastor — 500 g', 'Kilo completo $900. Incluye salsa roja, salsa verde, limones y tortillas.', 450, false, 2),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Pastor — 750 g', 'Kilo completo $900. Incluye salsa roja, salsa verde, limones y tortillas.', 675, false, 3),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Pastor — 1 kg', 'Kilo completo $900. Incluye salsa roja, salsa verde, limones y tortillas.', 900, false, 4),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Bistec de Res — 250 g', 'Kilo completo $1100. Incluye salsa roja, salsa verde, limones y tortillas.', 275, false, 5),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Bistec de Res — 500 g', 'Kilo completo $1100. Incluye salsa roja, salsa verde, limones y tortillas.', 550, false, 6),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Bistec de Res — 750 g', 'Kilo completo $1100. Incluye salsa roja, salsa verde, limones y tortillas.', 825, false, 7),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Bistec de Res — 1 kg', 'Kilo completo $1100. Incluye salsa roja, salsa verde, limones y tortillas.', 1100, false, 8),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Bistec de Res Encebollado — 250 g', 'Kilo completo $1150. Incluye salsa roja, salsa verde, limones y tortillas.', 287.5, false, 9),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Bistec de Res Encebollado — 500 g', 'Kilo completo $1150. Incluye salsa roja, salsa verde, limones y tortillas.', 575, false, 10),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Bistec de Res Encebollado — 750 g', 'Kilo completo $1150. Incluye salsa roja, salsa verde, limones y tortillas.', 862.5, false, 11),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Bistec de Res Encebollado — 1 kg', 'Kilo completo $1150. Incluye salsa roja, salsa verde, limones y tortillas.', 1150, false, 12),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Chuleta de Cerdo — 250 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 237.5, false, 13),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Chuleta de Cerdo — 500 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 475, false, 14),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Chuleta de Cerdo — 750 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 712.5, false, 15),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Chuleta de Cerdo — 1 kg', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 950, false, 16),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Pechuga de Pollo — 250 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 237.5, false, 17),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Pechuga de Pollo — 500 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 475, false, 18),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Pechuga de Pollo — 750 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 712.5, false, 19),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Pechuga de Pollo — 1 kg', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 950, false, 20),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Poc-Chuc — 250 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 237.5, false, 21),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Poc-Chuc — 500 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 475, false, 22),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Poc-Chuc — 750 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 712.5, false, 23),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Poc-Chuc — 1 kg', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 950, false, 24),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Arrachera — 250 g', 'Kilo completo $1400. Incluye salsa roja, salsa verde, limones y tortillas.', 350, false, 25),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Arrachera — 500 g', 'Kilo completo $1400. Incluye salsa roja, salsa verde, limones y tortillas.', 700, false, 26),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Arrachera — 750 g', 'Kilo completo $1400. Incluye salsa roja, salsa verde, limones y tortillas.', 1050, false, 27),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Arrachera — 1 kg', 'Kilo completo $1400. Incluye salsa roja, salsa verde, limones y tortillas.', 1400, false, 28),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Costilla de Res — 250 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 237.5, false, 29),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Costilla de Res — 500 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 475, false, 30),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Costilla de Res — 750 g', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 712.5, false, 31),
  ((SELECT id FROM public.categories WHERE slug = 'kilos'), 'Costilla de Res — 1 kg', 'Kilo completo $950. Incluye salsa roja, salsa verde, limones y tortillas.', 950, false, 32);
