// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // Implícito a propósito, no PKCE: PKCE vuelve con "?code=" y exige un
    // exchangeCodeForSession() que nadie llama a mano aquí — se resuelve
    // solo dentro del SDK, y si falla (code_verifier no encontrado, etc.) lo
    // hace en silencio y limpia la URL antes de que se note. El flujo
    // implícito vuelve con "#access_token=" en el hash, que AdminLogin.tsx
    // ya consume él mismo de forma explícita y con el error a la vista.
    flowType: 'implicit',
  }
});